version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: huoc_db
    ports:
      - "3306:3306"