version: "3.9"  # atualizado para suportar 'depends_on.condition'
services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: huoc
    ports:
      - "3306:3306"
    networks:
      - redehuoc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s  # tempo para o MySQL inicializar

  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - redehuoc

networks:
  redehuoc:
    driver: bridge
