version: "3"
services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: huoc
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
